from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Field, model_validator


class RecipeBase(BaseModel):
    """Shared fields for recipes."""
    title: str
    description: str
    # Ingredients mapping: ingredient name -> amount (float)
    ingredients: Dict[str, float]
    steps: List[str]
    prep_minutes: int = Field(ge=1, le=600, description="1–600 minutes")


class Recipe(RecipeBase):
    """Response model (includes ID generated by server)."""
    id: int


class RecipeCreate(RecipeBase):
    """Incoming payload for creating recipes."""

    @model_validator(mode="after")
    def normalize_title(self) -> "RecipeCreate":
        # Normalize title to Title Case and strip whitespace
        self.title = self.title.strip().title()
        return self
